from abc import ABC, abstractmethod
from typing import List, Dict, Any
from pydantic import BaseModel

class LLMClientInterface(ABC):
    """Interface for language model clients."""

    @abstractmethod
    def generate_response(self, prompt: str) -> Any:
        """
        Generates a response from the language model.

        Args:
            prompt: The prompt to send to the model.
            output_model: An optional Pydantic model to structure the response.

        Returns:
            The response generated by the model, possibly structured.
        """
        pass