# webapp_linker.py
import requests
import logging
# from .config import WEBAPP_API_LINK_URL, WEBAPP_BASE_URL # Import URLs
import json # Import json for better error logging of response body

logger = logging.getLogger(__name__)

def link_telegram_user_to_webapp(telegram_user_id: int, linking_token: str) -> str | None:
    """
    Calls the webapp backend API to link a Telegram user using a unique token.

    This token is generated by the webapp when the user clicks "Link Telegram"
    on the website, and sent to the bot via a Telegram deep link (/start?payload=...).

    Args:
        telegram_user_id: The ID of the Telegram user.
        linking_token: The unique, temporary token generated by the webapp.

    Returns:
        The webapp_user_id (as a string) if the linking is successful,
        None otherwise.
    """
    return True

# Add functions here later for actual data logging to webapp:
# def log_expense_to_webapp(webapp_user_id: str, date, description, amount, category): ...
# def log_income_to_webapp(webapp_user_id: str, date, description, amount, source): ...
# def log_currency_exchange_to_webapp(webapp_user_id: str, date, from_currency, to_currency, rate): ...