CREATE TABLE IF NOT EXISTS public.users (
    telegram_user_id BIGINT PRIMARY KEY,
    google_sheet_id TEXT NULL,           
    webapp_user_id TEXT UNIQUE NULL,     
    webapp_integration_id TEXT UNIQUE NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), 
    last_interaction_at TIMESTAMP WITH TIME ZONE NULL, 
    telegram_username TEXT NULL,        
    telegram_first_name TEXT NOT NULL,  
    telegram_last_name TEXT NULL         
);

COMMENT ON TABLE public.users IS 'Stores bot users and their linked data storage options.';
COMMENT ON COLUMN public.users.telegram_user_id IS 'Unique identifier from Telegram.';
COMMENT ON COLUMN public.users.google_sheet_id IS 'ID of the user''s linked Google Sheet.';
COMMENT ON COLUMN public.users.webapp_user_id IS 'Internal ID of the user in the linked Webapp backend.';
COMMENT ON COLUMN public.users.webapp_integration_id IS 'Unique alphanumeric ID generated by Webapp to link Telegram user.';
COMMENT ON COLUMN public.users.created_at IS 'Timestamp when the user first interacted.';
COMMENT ON COLUMN public.users.last_interaction_at IS 'Timestamp of the user''s last message/command.';
COMMENT ON COLUMN public.users.telegram_username IS 'Telegram username (can be NULL or change).';
COMMENT ON COLUMN public.users.telegram_first_name IS 'Telegram first name.';
COMMENT ON COLUMN public.users.telegram_last_name IS 'Telegram last name.';

CREATE UNIQUE INDEX idx_users_webapp_user_id ON public.users (webapp_user_id) WHERE webapp_user_id IS NOT NULL;
CREATE UNIQUE INDEX idx_users_webapp_integration_id ON public.users (webapp_integration_id) WHERE webapp_integration_id IS NOT NULL;